# 端口
server:
  port: 8088


# 配置数据库连接的账号、密码、url、数据库驱动
spring:
    datasource:
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/bookstore
 
# 使用mybatis操作数据库配置以下内容
mybatis:
    type-aliases-package: com.it.mapper  #可以添加此属性
    mapper-locations: classpath:com/it/mapper/*xml # 指定配置mapper文件的位置


# 配置pagehelper参数
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql